# Generated by Django 5.2.6 on 2025-09-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(blank=True)),
                ('resume_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('R', 'Reviewed'), ('X', 'Rejected')], default='P', max_length=1)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
